## Prim's Algorithm 


- input from **graph.txt** file.
- Representation - **ADJACNECY MATRIX**.
- Task - **Finding MST using Prim's Algorithm**.

In [15]:
try:
    graph = open("D:\III semester\Algorithms\Assignment 4\graph.txt",'r+')
except:
    print("File is not opening correctly, re-check path or filename")

import time as time
import numpy as np
def make_adj(nodes):
    '''To make an adjacency matrix'''
    mat = np.zeros((nodes,nodes))
    return np.matrix(mat)

for row in graph:
    if(len(row)==2):
        nodes = int(row[0])
        adj = make_adj(nodes)
    else:
        w = int(row[4])
        u = int(ord(row[0]) - 65)
        v = int(ord(row[2]) - 65)
        adj[u,v] = w
        adj[v,u] = w
        print("Start :",u," End :",v,"Weight:",w)
graph.seek(0)
print("\nAdjacency Matrix is :")
print(adj,"\n")
print("Calculating")
for i in range(10):
    print(".",end="")
    time.sleep(0.1)
    print(".",end="")
    time.sleep(0.1)
    print(".",end="")
    #print("\r",end="")
    print("\r\r\r",end="")
print("\r")  
time.sleep(3)
# Minimum vertex finding
def find_min(dist,visited):
    mini = 1e18
    for i in dist:
        if(visited[i]==False):
            if(dist[i]<mini and dist[i]>0):
                ind = i
                mini = dist[i]
    return ind
# function for Prim's
def prims(adj):
    '''Parameters: adj-> Adjacency Mtatrix for the graph
       Variables: total-> Total weight of MST
                  parent-> Dictionary storing parents of each node
                  visit-> boolean array to store which vertex has been included
                          in the MST
                  MST-> The minimum spanning tree of the graph containing a tuple
                          Source - Destination - Weight
       Returns : A tuple of total and MST'''
    total = 0
    parent = {}
    d = {}
    visit = []# has zero based indexing
    for i in range(len(adj)):
        visit.append(False)
        parent[i] = -1
        d[i] = 1e18
    MST = []
    visit[0] = True
    # Updating for the starting node
    for i in range(1,len(adj)):# skipping i = 0
        if(adj[0,i]!=0):
            parent[i] = 0
            d[i] = adj[0,i]
    print("Distances:",d)
    print("Parents:",parent)
    for i in range(1,len(adj)):
        u = find_min(d,visit) # u is zero based
        print("Current :",u)
        # u is the vertex which is minimum and not visited yet.
        visit[u] = True
        MST.append((u,parent[u],d[u]))
        total+= d[u]
        for k in range(len(adj)):
            if(visit[k]==False and d[k] > adj[u,k] and adj[u,k]>0):
                d[k] = adj[u,k]
                parent[k] = u
                print(k," is updated")
                print("Distances:",d)
                print("Parents:",parent)
    print("\nThe Minimum spanning tree is :")
    return MST,total


prims(adj)

Start : 0  End : 1 Weight: 5
Start : 0  End : 2 Weight: 4
Start : 0  End : 3 Weight: 2
Start : 1  End : 2 Weight: 3
Start : 3  End : 4 Weight: 1

Adjacency Matrix is :
[[0. 5. 4. 2. 0.]
 [5. 0. 3. 0. 0.]
 [4. 3. 0. 0. 0.]
 [2. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]] 

Calculating
........
Distances: {0: 1e+18, 1: 5.0, 2: 4.0, 3: 2.0, 4: 1e+18}
Parents: {0: -1, 1: 0, 2: 0, 3: 0, 4: -1}
Current : 3
4  is updated
Distances: {0: 1e+18, 1: 5.0, 2: 4.0, 3: 2.0, 4: 1.0}
Parents: {0: -1, 1: 0, 2: 0, 3: 0, 4: 3}
Current : 4
Current : 2
1  is updated
Distances: {0: 1e+18, 1: 3.0, 2: 4.0, 3: 2.0, 4: 1.0}
Parents: {0: -1, 1: 2, 2: 0, 3: 0, 4: 3}
Current : 1

The Minimum spanning tree is :


([(3, 0, 2.0), (4, 3, 1.0), (2, 0, 4.0), (1, 2, 3.0)], 10.0)