# Dijkstra's Algorithm.
- Implementing Dijkstra's algorithm to find the single source shortest path to all vertices given a particular starting vertex s and an adjacency matrix adj for the graph

In [1]:
import numpy as np
import math
import time
import functools

In [2]:
def make_adj(nodes):
    mat = np.zeros((nodes,nodes))
    return np.matrix(mat)

In [3]:
try:
    graph = open("D:\III semester\Algorithms\Dijkstra's\Graph.txt",'r+')
except:
    print("Can't open file. Try checking name or the path of the file")

In [4]:
print("Reading graph...")
time.sleep(0.8)
for row in graph:
    if(len(row)==2):
        nodes = int(row[0])
        adj = make_adj(nodes)
    else:
        data= row.split(',')
        u = int(data[0])
        v = int(data[1])
        w = int(data[2])
        print("Start :",u," End :",v," Weight :",w)
        time.sleep(0.3)
        adj[u,v] = w
        adj[v,u] = w
graph.seek(0)
print("Adjacency matrix formed.\nADJACENCY MATRIX :\n")
print(adj)
    

Reading graph...
Start : 0  End : 1  Weight : 10
Start : 0  End : 2  Weight : 80
Start : 1  End : 2  Weight : 6
Start : 1  End : 4  Weight : 20
Start : 2  End : 3  Weight : 70
Start : 4  End : 5  Weight : 30
Start : 4  End : 6  Weight : 10
Start : 5  End : 6  Weight : 5
Adjacency matrix formed.
ADJACENCY MATRIX :

[[ 0. 10. 80.  0.  0.  0.  0.]
 [10.  0.  6.  0. 20.  0.  0.]
 [80.  6.  0. 70.  0.  0.  0.]
 [ 0.  0. 70.  0.  0.  0.  0.]
 [ 0. 20.  0.  0.  0. 30. 10.]
 [ 0.  0.  0.  0. 30.  0.  5.]
 [ 0.  0.  0.  0. 10.  5.  0.]]


In [5]:
def find_min_vertex(d,visited):
    mini = 1e18
    for i in range(len(visited)):
        if(visited[i]==False):
            if(d[i]<mini):
                mini = d[i]
                ind = i
    return ind #zero based


def dijkstra(nodes,adj,s):
    '''Parameters: nodes-> the total nodes in the graph
                    adj-> Adjaceny matrix of the graph
                    s-> source vertex.
        Return Signature: d-> Distance array (shortest path of all
        vertices from s)
                         parent-> Parent pointers specifying the path 
                         which is the shortest'''
    d = {}
    visited=[]
    parent = {}
    # Initialisation
    for i in range(nodes):
        d[i] = 1e18
        visited.append(False)
        parent[i] = -1
    
    # set distance of Source as 0
    d[s] = 0
    total = 0
    while(total<nodes):
        u = find_min_vertex(d,visited)
        # u is the current vertex which is not yet visited and has the minimum
        # path amongst all the vertices
        visited[u] = True
        total +=1
        for i in range(nodes):
            if(visited[i]== False):
                if(adj[u,i]>0 and d[i] > d[u] + adj[u,i]):
                    d[i]= d[u] + adj[u,i]
                    parent[i] = u
                    print("Distances updated.")
                    print("Array is :",d)
    
    return d,parent    
    
    

In [6]:
while(1):
    s = int(input("Enter source vertex :"))
    if(s<0 or s>=nodes):
        print("Invalid vertex. Enter again")
    else:
        break
dist , parents = dijkstra(nodes,adj,s)

Enter source vertex :6
Distances updated.
Array is : {0: 1e+18, 1: 1e+18, 2: 1e+18, 3: 1e+18, 4: 10.0, 5: 1e+18, 6: 0}
Distances updated.
Array is : {0: 1e+18, 1: 1e+18, 2: 1e+18, 3: 1e+18, 4: 10.0, 5: 5.0, 6: 0}
Distances updated.
Array is : {0: 1e+18, 1: 30.0, 2: 1e+18, 3: 1e+18, 4: 10.0, 5: 5.0, 6: 0}
Distances updated.
Array is : {0: 40.0, 1: 30.0, 2: 1e+18, 3: 1e+18, 4: 10.0, 5: 5.0, 6: 0}
Distances updated.
Array is : {0: 40.0, 1: 30.0, 2: 36.0, 3: 1e+18, 4: 10.0, 5: 5.0, 6: 0}
Distances updated.
Array is : {0: 40.0, 1: 30.0, 2: 36.0, 3: 106.0, 4: 10.0, 5: 5.0, 6: 0}


In [7]:
print("Distances are :",dist)
print("Parent pointers :",parents)

Distances are : {0: 40.0, 1: 30.0, 2: 36.0, 3: 106.0, 4: 10.0, 5: 5.0, 6: 0}
Parent pointers : {0: 1, 1: 4, 2: 1, 3: 2, 4: 6, 5: 6, 6: -1}


In [8]:
while(1):
    vertex = int(input("Enter vertex to find path:"))
    if(s<0 or s>nodes):
        print("Invalid vertex. Enter again")
    else:
        break
i = vertex
while(i!=-1):
    print(i,"-> ",end="")
    i = parents[i]

Enter vertex to find path:0
0 -> 1 -> 4 -> 6 -> 