# Bellman Ford's Algorithm
- Finding single source shortest paths for a given graph and a vertex s.
- Given - A graph file with edges .
- It works even for negative edges (**in directed graphs**).
- Only condition is that the graph should not contain negative weight cycles as that cycle may act as a vortex to decrease your path infinitely as you try to find the shortest route.
- Iterations for the algorithm are equal to number of nodes - 1.

In [1]:
import numpy as np
import math
import time

In [36]:
graph = open("D:\III semester\Algorithms\Bellman Ford's\Graph.txt",'r+')

In [37]:
def make_adj(nodes):
    mat = np.zeros((nodes,nodes))
    return (np.matrix(mat))

In [60]:
print("Reading graph...")
time.sleep(0.5)
adj_list = {}
for row in graph:
    if(len(row)==2):
        nodes = int(row[0])
        adj = make_adj(nodes)
        for i in range(nodes):
            adj_list[i] =[]
    else:
        data = row.split(",")
        u = int(data[0])
        v = int(data[1])
        w = int(data[2])
        adj_list[u].append((v,w))
        adj[u,v] = w
        print("Source :",u,"Destination :",v,"Weight :",w)
        time.sleep(0.4)
graph.seek(0)
print("Adjacency matrix is :\n",adj)
print("Adjacency list is :\n",adj_list)

Reading graph...
Source : 0 Destination : 1 Weight : 10
Source : 0 Destination : 7 Weight : 8
Source : 1 Destination : 5 Weight : 2
Source : 2 Destination : 1 Weight : 1
Source : 2 Destination : 3 Weight : 1
Source : 3 Destination : 4 Weight : 3
Source : 4 Destination : 5 Weight : -1
Source : 5 Destination : 2 Weight : -2
Source : 6 Destination : 5 Weight : -1
Source : 6 Destination : 1 Weight : -4
Source : 7 Destination : 6 Weight : 1
Adjacency matrix is :
 [[ 0. 10.  0.  0.  0.  0.  0.  8.]
 [ 0.  0.  0.  0.  0.  2.  0.  0.]
 [ 0.  1.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  3.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0. -2.  0.  0.  0.  0.  0.]
 [ 0. -4.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]]
Adjacency list is :
 {0: [(1, 10), (7, 8)], 1: [(5, 2)], 2: [(1, 1), (3, 1)], 3: [(4, 3)], 4: [(5, -1)], 5: [(2, -2)], 6: [(5, -1), (1, -4)], 7: [(6, 1)]}


In [62]:
def bellman_ford_opt(source,nodes,adj_list):
    '''Adjacency list implementation'''
    d ={}
    parent = {}
    for i in range(nodes):
        d[i] = 1e18
        parent[i] = -1
    # now make the distance of the source as zero
    d[source] = 0
    for i in range(nodes-1):# this is because any shortest path can have at max n-1 edges
        for j in range(nodes):# to access the ith vertex
            for f in adj_list[j]:# to access the row of that ith vertex
                v = f[0]
                w = f[1]
                d[v] = min(d[v],d[j]+w)
                parent[v] = j
        print("After iteration",i+1)
        print("Distances :",d)
        print("Parents :",parent)
    return d,parent
    

In [66]:
def bellman_ford(source,nodes,adj):
    '''Adjacency matrix implementation'''
    d ={}
    parent = {}
    for i in range(nodes):
        d[i] = 1e18
        parent[i] = -1
    # now make the distance of the source as zero
    
    d[source] = 0
    for i in range(nodes-1):# this is because any shortest path can have at max n-1 edges
        for j in range(nodes):# to access the ith vertex
            for f in range(nodes): # to access the row of that ith vertex
                if(adj[j,f]!=0):
                    d[f] = min(d[f], d[j] + adj[j,f])# j is the parent
                    parent[f] = j
        print("After iteration",i+1)
        print("Distances :",d)
        print("Parents :",parent)
    return d,parent
                

In [67]:
while(1):
    s = int(input("Enter the source vertex :"))
    if(s<0 or s>=nodes):
        print("Invalid vertex. Enter again")
    else:
        break

Enter the source vertex :1


In [68]:
%time
paths, parents = bellman_ford(s,nodes,adj)

Wall time: 0 ns
After iteration 1
Distances : {0: 1e+18, 1: 0, 2: 0.0, 3: 1e+18, 4: 1e+18, 5: 2.0, 6: 1e+18, 7: 1e+18}
Parents : {0: -1, 1: 6, 2: 5, 3: 2, 4: 3, 5: 6, 6: 7, 7: 0}
After iteration 2
Distances : {0: 1e+18, 1: 0, 2: 0.0, 3: 1.0, 4: 4.0, 5: 2.0, 6: 1e+18, 7: 1e+18}
Parents : {0: -1, 1: 6, 2: 5, 3: 2, 4: 3, 5: 6, 6: 7, 7: 0}
After iteration 3
Distances : {0: 1e+18, 1: 0, 2: 0.0, 3: 1.0, 4: 4.0, 5: 2.0, 6: 1e+18, 7: 1e+18}
Parents : {0: -1, 1: 6, 2: 5, 3: 2, 4: 3, 5: 6, 6: 7, 7: 0}
After iteration 4
Distances : {0: 1e+18, 1: 0, 2: 0.0, 3: 1.0, 4: 4.0, 5: 2.0, 6: 1e+18, 7: 1e+18}
Parents : {0: -1, 1: 6, 2: 5, 3: 2, 4: 3, 5: 6, 6: 7, 7: 0}
After iteration 5
Distances : {0: 1e+18, 1: 0, 2: 0.0, 3: 1.0, 4: 4.0, 5: 2.0, 6: 1e+18, 7: 1e+18}
Parents : {0: -1, 1: 6, 2: 5, 3: 2, 4: 3, 5: 6, 6: 7, 7: 0}
After iteration 6
Distances : {0: 1e+18, 1: 0, 2: 0.0, 3: 1.0, 4: 4.0, 5: 2.0, 6: 1e+18, 7: 1e+18}
Parents : {0: -1, 1: 6, 2: 5, 3: 2, 4: 3, 5: 6, 6: 7, 7: 0}
After iteration 7
Distance

In [69]:
print("Shortest paths are :",paths)

Shortest paths are : {0: 1e+18, 1: 0, 2: 0.0, 3: 1.0, 4: 4.0, 5: 2.0, 6: 1e+18, 7: 1e+18}


In [70]:
%time
dist,par = bellman_ford_opt(s,nodes,adj_list)

Wall time: 0 ns
After iteration 1
Distances : {0: 1e+18, 1: 0, 2: 0, 3: 1e+18, 4: 1e+18, 5: 2, 6: 1e+18, 7: 1e+18}
Parents : {0: -1, 1: 6, 2: 5, 3: 2, 4: 3, 5: 6, 6: 7, 7: 0}
After iteration 2
Distances : {0: 1e+18, 1: 0, 2: 0, 3: 1, 4: 4, 5: 2, 6: 1e+18, 7: 1e+18}
Parents : {0: -1, 1: 6, 2: 5, 3: 2, 4: 3, 5: 6, 6: 7, 7: 0}
After iteration 3
Distances : {0: 1e+18, 1: 0, 2: 0, 3: 1, 4: 4, 5: 2, 6: 1e+18, 7: 1e+18}
Parents : {0: -1, 1: 6, 2: 5, 3: 2, 4: 3, 5: 6, 6: 7, 7: 0}
After iteration 4
Distances : {0: 1e+18, 1: 0, 2: 0, 3: 1, 4: 4, 5: 2, 6: 1e+18, 7: 1e+18}
Parents : {0: -1, 1: 6, 2: 5, 3: 2, 4: 3, 5: 6, 6: 7, 7: 0}
After iteration 5
Distances : {0: 1e+18, 1: 0, 2: 0, 3: 1, 4: 4, 5: 2, 6: 1e+18, 7: 1e+18}
Parents : {0: -1, 1: 6, 2: 5, 3: 2, 4: 3, 5: 6, 6: 7, 7: 0}
After iteration 6
Distances : {0: 1e+18, 1: 0, 2: 0, 3: 1, 4: 4, 5: 2, 6: 1e+18, 7: 1e+18}
Parents : {0: -1, 1: 6, 2: 5, 3: 2, 4: 3, 5: 6, 6: 7, 7: 0}
After iteration 7
Distances : {0: 1e+18, 1: 0, 2: 0, 3: 1, 4: 4, 5: 2,